# Schema for configuration files of the Entity Language Fallback.

language.entity.*.third_party.entity_language_fallback:
  type: mapping
  label: 'Per language entity fallback settings'
  mapping:
    fallback_langcodes:
      type: sequence
      label: 'Fallback language codes'
      sequence:
        type: string
        label: 'Fallback language code'
